[FE-25] Create script to GET requester pays status of a workspace bucket
broadinstitute/horsefish pull request #135
Opened 2023-05-02 17:36 UTC by samanthahv

https://broadworkbench.atlassian.net/browse/FE-25

2023-05-02 17:41 UTC, mmorgantaylor commented
looks good! can you demonstrate some testing by running the script on both a RP and non-RP bucket and showing the script's output in the PR description?

2023-05-02 17:46 UTC, samanthahv commented
@mmorgantaylor i added a screenshot of the output for a non-RP bucket to the Jira ticket, but i can add it to this PR description along with a screenshot for a RP-enabled bucket

2023-05-02 17:50 UTC, samanthahv commented
@mmorgantaylor done!

2023-05-02 18:17 UTC, mmorgantaylor requested changes
a couple questions/requests!

2023-05-02 20:04 UTC, samanthahv commented
addressed your comments in this commit [46cf4e3](https://github.com/broadinstitute/horsefish/pull/135/commits/46cf4e3a27f2840aa64d0e29840f56e87ebfa497)

2023-05-03 13:54 UTC, mmorgantaylor commented on scripts/get_requester_pays_status.sh
> +  echo "i.e you can run ./set_requester_pays.sh on project_id fc-12345"
change to `./get_requester_pays.sh`

2023-05-03 13:56 UTC, mmorgantaylor commented on scripts/get_requester_pays_status.sh
> +  echo "i.e you can run ./set_requester_pays.sh on project_id fc-12345"
also remove the word "on" in the command and add backticks - so I think this line should be 
```echo "i.e you can run `./get_requester_pays.sh project_id fc-12345`"```

2023-05-03 17:59 UTC, merged