Create gcs-inventory-loader.ipynb
broadinstitute/horsefish pull request #47
Opened 2021-04-27 19:18 UTC by Marianie-Simeon

Created a motebook that uses gcs-inventory-loader

2021-05-04 16:11 UTC, schaluva requested changes

2021-05-04 16:11 UTC, schaluva commented on scripts/gcs-inventory-loader.ipynb
> +    "\n",
The introduction is great! However, if I had never used it before I think it is a tiny bit confusing what is actually happening in the notebook so maybe a summary section like:
1. Set up the Notebook
2. Load your workspace bucket to a BQ project
3. Visualize object metadata


Also maybe a note or two about how they have to come to this notebook with a BQ project and dataset already created.

2021-05-04 16:11 UTC, schaluva commented on scripts/gcs-inventory-loader.ipynb
> +    "- INVENTORY_TABLE=The_BigQuery_Table\n",
Also - a few more words to define the variables. For example `"INVENTORY_TABLE" is what they want to call the resulting table of gcs-inventory-loader where the object metadata will be uploaded`

2021-05-07 22:09 UTC, mmorgantaylor commented on scripts/gcs-inventory-loader.ipynb
> +    "%matplotlib inline"
you only need to run the `%matplotlib inline` command once - you've already run it up above, no need to re-run here (can delete this cell)

2021-05-10 21:28 UTC, mmorgantaylor commented
i'll go look it up from the ticket now, but for PRs that involve notebooks, could you in future put the Terra version of the notebook into the PR description? that would make reviewing it much easier!!

2023-08-01 13:48 UTC, closed without merging